# netlify.toml

[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.4"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add this entire section below
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"